import { Geist, Geist_Mono, Open_Sans } from 'next/font/google';
import './globals.css';
import 'react-toastify/dist/ReactToastify.css';
import Provider from './provider';
import ConvexClientProvider from './ConvexClientProvider';
import { ToastContainer } from 'react-toastify';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const openSans = Open_Sans({ subsets: ['latin', 'vietnamese'] });

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body className={openSans.className}>
        <ConvexClientProvider>
          {children}
          <ToastContainer
            position="top-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
          />
        </ConvexClientProvider>
      </body>
    </html>
  );
}
